In [1]:
import numpy as np
import pandas as pd
from pandas_datareader import data as wb

In [8]:
stock_list = ['MSFT', 'AAPL']

close_data = pd.DataFrame()

for stock in stock_list:
    close_data[stock] = wb.DataReader(stock, data_source='yahoo', \
                                      start='2019-01-01', end='2019-01-10')['Adj Close']

close_data

MSFT        AAPL
Date                              
2019-01-02  100.318642  156.642365
2019-01-03   96.628120  141.039642
2019-01-04  101.122223  147.060516
2019-01-07  101.251190  146.733185
2019-01-08  101.985329  149.530380
2019-01-09  103.443672  152.069672
2019-01-10  102.778984  152.555710
2019-01-11  101.985329  151.057922

In [9]:
price_1 = close_data.as_matrix()

/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


In [10]:
return_df = close_data.pct_change()
return_df = return_df[1:]
return_df

MSFT      AAPL
Date                          
2019-01-03 -0.036788 -0.099607
2019-01-04  0.046509  0.042689
2019-01-07  0.001275 -0.002226
2019-01-08  0.007251  0.019063
2019-01-09  0.014300  0.016982
2019-01-10 -0.006426  0.003196
2019-01-11 -0.007722 -0.009818

In [11]:
return_df.iloc[2,0] = 0.0012
return_df.iloc[3,1] = 0.02

In [13]:
return_arr = return_df.as_matrix()

/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


In [14]:
return_arr

array([[-0.03678799, -0.09960729],
       [ 0.04650926,  0.04268923],
       [ 0.0012    , -0.00222583],
       [ 0.00725067,  0.02      ],
       [ 0.01429954,  0.01698178],
       [-0.0064256 ,  0.00319615],
       [-0.00772196, -0.00981797]])

In [15]:
price_2 = np.zeros_like(close_data.as_matrix())

/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


In [16]:
price_2[0] = close_data.iloc[0].as_matrix()

for t in range(1, close_data.shape[0]):
    price_2[t] = price_2[t-1]*(1.0 + return_arr[t-1])

/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


In [17]:
price_2

array([[100.31864166, 156.6423645 ],
       [ 96.62812042, 141.03964233],
       [101.1222229 , 147.06051636],
       [101.24356957, 146.73318481],
       [101.9776528 , 149.66784851],
       [103.43588655, 152.20947435],
       [102.77124846, 152.69595939],
       [101.9776528 , 151.19679495]])

In [18]:
x = price_1 - price_2
x

array([[ 0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00, -2.84217094e-14],
       [ 7.62061768e-03, -2.84217094e-14],
       [ 7.67587222e-03, -1.37468262e-01],
       [ 7.78563368e-03, -1.39802717e-01],
       [ 7.73560628e-03, -1.40249548e-01],
       [ 7.67587222e-03, -1.38872582e-01]])